# Generated by Django 2.2 on 2019-04-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_perm_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel_perm_user',
            name='test',
        ),
    ]
